on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Haskell CI
jobs:
  runhaskell:
    name: PeepingTom
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.1' # Resolves to the latest point release of GHC 8.8
          cabal-version: '3.10.1.0' # Exact version of Cabal
      - name: Clone ScanMem
        run: git clone https://github.com/scanmem/scanmem.git test/scanmem
      - name: Install requirements
        run: sudo apt install autotools-dev libtool libreadline-dev intltool python3
      - name: Build ScanMem
        run: |
          cd test/scanmem/
          ./autogen.sh
          mkdir -p build && cd build
          ../configure
          make
      - name: Build PeepingTom
        run: cabal build
      - name: Run Tests
        run: LD_LIBRARY_PATH="$PWD/test/scanmem/build/.libs/:$LD_LIBRARY_PATH" cabal test
